import {UnitListModel} from "./types";

export const unitListDummyData: UnitListModel[] = [
    {
        year: "2024",
        grade: "7",
        maxStudents: "54",
        maxSessions: "45",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "15/07/2024",
        classes: "2",
    },
    {
        year: "2023",
        grade: "12",
        maxStudents: "53",
        maxSessions: "55",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "21/08/2023",
        classes: "3",
    },
    {
        year: "2022",
        grade: "9",
        maxStudents: "44",
        maxSessions: "60",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "19/02/2022",
        classes: "5",
    },
    {
        year: "2021",
        grade: "5",
        maxStudents: "52",
        maxSessions: "50",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "10/06/2021",
        classes: "1",
    },
    {
        year: "2025",
        grade: "11",
        maxStudents: "40",
        maxSessions: "60",
        pricePerSession: "10$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "03/03/2025",
        classes: "6",
    },
    {
        year: "2020",
        grade: "2",
        maxStudents: "50",
        maxSessions: "45",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "12/11/2020",
        classes: "0",
    },
    {
        year: "2023",
        grade: "4",
        maxStudents: "48",
        maxSessions: "55",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "30/12/2023",
        classes: "4",
    },
    {
        year: "2021",
        grade: "10",
        maxStudents: "47",
        maxSessions: "50",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "06/05/2021",
        classes: "3",
    },
    {
        year: "2024",
        grade: "3",
        maxStudents: "53",
        maxSessions: "60",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "18/10/2024",
        classes: "1",
    },
    {
        year: "2020",
        grade: "8",
        maxStudents: "55",
        maxSessions: "55",
        pricePerSession: "10$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "22/04/2020",
        classes: "2",
    },
    {
        year: "2025",
        grade: "6",
        maxStudents: "52",
        maxSessions: "45",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "09/09/2025",
        classes: "7",
    },
    {
        year: "2022",
        grade: "1",
        maxStudents: "51",
        maxSessions: "50",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "14/01/2022",
        classes: "0",
    },
    {
        year: "2021",
        grade: "7",
        maxStudents: "46",
        maxSessions: "45",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "05/07/2021",
        classes: "4",
    },
    {
        year: "2020",
        grade: "12",
        maxStudents: "44",
        maxSessions: "60",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "28/08/2020",
        classes: "5",
    },
    {
        year: "2024",
        grade: "4",
        maxStudents: "54",
        maxSessions: "55",
        pricePerSession: "10$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "11/06/2024",
        classes: "2",
    },
    {
        year: "2023",
        grade: "11",
        maxStudents: "40",
        maxSessions: "50",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "17/02/2023",
        classes: "3",
    },
    {
        year: "2022",
        grade: "5",
        maxStudents: "48",
        maxSessions: "55",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "25/05/2022",
        classes: "1",
    },
    {
        year: "2025",
        grade: "9",
        maxStudents: "45",
        maxSessions: "45",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "12/10/2025",
        classes: "6",
    },
    {
        year: "2021",
        grade: "6",
        maxStudents: "53",
        maxSessions: "60",
        pricePerSession: "10$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "04/12/2021",
        classes: "0",
    },
    {
        year: "2023",
        grade: "8",
        maxStudents: "51",
        maxSessions: "50",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "30/11/2023",
        classes: "3",
    },
    {
        year: "2020",
        grade: "3",
        maxStudents: "49",
        maxSessions: "55",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "16/01/2020",
        classes: "1",
    },
    {
        year: "2024",
        grade: "10",
        maxStudents: "42",
        maxSessions: "60",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "29/03/2024",
        classes: "5",
    },
    {
        year: "2022",
        grade: "7",
        maxStudents: "47",
        maxSessions: "50",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "11/09/2022",
        classes: "2",
    },
    {
        year: "2025",
        grade: "1",
        maxStudents: "50",
        maxSessions: "45",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "05/04/2025",
        classes: "6",
    },
    {
        year: "2020",
        grade: "9",
        maxStudents: "48",
        maxSessions: "55",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "23/05/2020",
        classes: "0",
    },
    {
        year: "2023",
        grade: "2",
        maxStudents: "44",
        maxSessions: "50",
        pricePerSession: "10$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "20/07/2023",
        classes: "4",
    },
    {
        year: "2021",
        grade: "11",
        maxStudents: "46",
        maxSessions: "60",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "02/08/2021",
        classes: "2",
    },
    {
        year: "2024",
        grade: "5",
        maxStudents: "52",
        maxSessions: "55",
        pricePerSession: "8$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "09/11/2024",
        classes: "1",
    },
    {
        year: "2020",
        grade: "10",
        maxStudents: "43",
        maxSessions: "50",
        pricePerSession: "7$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "15/03/2020",
        classes: "6",
    },
    {
        year: "2025",
        grade: "6",
        maxStudents: "41",
        maxSessions: "60",
        pricePerSession: "10$",
        studyTime: {
            studyHour: "2",
            studyMinute: "30",
            studySecond: "00",
        },
        createdTime: "14/10/2025",
        classes: "0",
    },
    {
        year: "2023",
        grade: "3",
        maxStudents: "54",
        maxSessions: "55",
        pricePerSession: "9$",
        studyTime: {
            studyHour: "2",
            studyMinute: "00",
            studySecond: "00",
        },
        createdTime: "01/01/2023",
        classes: "7",
    },
];
