import {StudentInfo} from "./types";

export const StudentDummyData: StudentInfo[] = [
    {
        index: "1",
        fullName: "Nguyễn Minh Đức",
        email: "EN3101",
        birthday: "19/01/2003",
        tuitionPaid: "true",
    },
    {
        index: "2",
        fullName: "Trần Thị Minh Thư",
        email: "EN3102",
        birthday: "05/03/2003",
        tuitionPaid: "false",
    },
    {
        index: "3",
        fullName: "Lê Anh Tuấn",
        email: "EN3103",
        birthday: "11/02/2003",
        tuitionPaid: "true",
    },
    {
        index: "4",
        fullName: "Phạm Thị Lan",
        email: "EN3104",
        birthday: "23/07/2003",
        tuitionPaid: "false",
    },
    {
        index: "5",
        fullName: "Nguyễn Văn Nam",
        email: "EN3105",
        birthday: "15/04/2003",
        tuitionPaid: "true",
    },
    {
        index: "6",
        fullName: "Hoàng Thị Bích",
        email: "EN3106",
        birthday: "30/05/2003",
        tuitionPaid: "true",
    },
    {
        index: "7",
        fullName: "Đặng Văn Hùng",
        email: "EN3107",
        birthday: "09/01/2003",
        tuitionPaid: "false",
    },
    {
        index: "8",
        fullName: "Bùi Thị Hằng",
        email: "EN3108",
        birthday: "14/02/2003",
        tuitionPaid: "true",
    },
    {
        index: "9",
        fullName: "Vũ Văn Hải",
        email: "EN3109",
        birthday: "25/03/2003",
        tuitionPaid: "false",
    },
    {
        index: "10",
        fullName: "Phạm Thị Mai",
        email: "EN3110",
        birthday: "12/04/2003",
        tuitionPaid: "true",
    },
    {
        index: "11",
        fullName: "Lý Minh Khoa",
        email: "EN3111",
        birthday: "28/06/2003",
        tuitionPaid: "true",
    },
];
