import {StudentListModel} from "./types";

export const studentListDummyData: StudentListModel[] = [
    {
        fullName: "Nguyễn Văn An",
        email: "dummyemail1@gmail.com",
        phoneNumber: "0912345670",
        birthday: "2006-05-15",
        status: "Deleted",
        hasDesireClass: "true",
    },
    {
        fullName: "Trần Thị Bích",
        email: "dummyemail2@gmail.com",
        phoneNumber: "0923456781",
        birthday: "2008-11-20",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Lê Minh Châu",
        email: "dummyemail3@gmail.com",
        phoneNumber: "0934567892",
        birthday: "2010-03-30",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Phạm Thanh Đăng",
        email: "dummyemail4@gmail.com",
        phoneNumber: "0945678903",
        birthday: "2007-07-14",
        status: "Deleted",
        hasDesireClass: "true",
    },
    {
        fullName: "Hoàng Thị Nga",
        email: "dummyemail5@gmail.com",
        phoneNumber: "0956789014",
        birthday: "2005-12-25",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Vũ Anh Đức",
        email: "dummyemail6@gmail.com",
        phoneNumber: "0967890125",
        birthday: "2009-01-10",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Đặng Thị Hạnh",
        email: "dummyemail7@gmail.com",
        phoneNumber: "0978901236",
        birthday: "2011-04-18",
        status: "Deleted",
        hasDesireClass: "true",
    },
    {
        fullName: "Bùi Ngọc Hà",
        email: "dummyemail8@gmail.com",
        phoneNumber: "0989012347",
        birthday: "2006-09-02",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Phan Thanh Lan",
        email: "dummyemail9@gmail.com",
        phoneNumber: "0901234568",
        birthday: "2005-05-19",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Ngô Thị Quỳnh",
        email: "dummyemail10@gmail.com",
        phoneNumber: "0912345679",
        birthday: "2008-10-22",
        status: "Deleted",
        hasDesireClass: "false",
    },
    {
        fullName: "Dương Anh Tú",
        email: "dummyemail11@gmail.com",
        phoneNumber: "0923456780",
        birthday: "2007-02-14",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Lý Thị Hương",
        email: "dummyemail12@gmail.com",
        phoneNumber: "0934567891",
        birthday: "2010-06-28",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Nguyễn Quốc Bảo",
        email: "dummyemail13@gmail.com",
        phoneNumber: "0945678902",
        birthday: "2009-08-30",
        status: "Deleted",
        hasDesireClass: "false",
    },
    {
        fullName: "Trần Khánh Hòa",
        email: "dummyemail14@gmail.com",
        phoneNumber: "0956789013",
        birthday: "2005-03-12",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Lê Minh Hiếu",
        email: "dummyemail15@gmail.com",
        phoneNumber: "0967890124",
        birthday: "2008-12-05",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Phạm Thanh Mai",
        email: "dummyemail16@gmail.com",
        phoneNumber: "0978901235",
        birthday: "2010-09-09",
        status: "Deleted",
        hasDesireClass: "false",
    },
    {
        fullName: "Hoàng Đức Phú",
        email: "dummyemail17@gmail.com",
        phoneNumber: "0989012346",
        birthday: "2006-11-13",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Vũ Thị Thu",
        email: "dummyemail18@gmail.com",
        phoneNumber: "0901234567",
        birthday: "2007-05-07",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Đặng Văn Toàn",
        email: "dummyemail19@gmail.com",
        phoneNumber: "0912345678",
        birthday: "2008-08-11",
        status: "Deleted",
        hasDesireClass: "false",
    },
    {
        fullName: "Bùi Thị Vân",
        email: "dummyemail20@gmail.com",
        phoneNumber: "0923456789",
        birthday: "2009-03-03",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Phan Anh Vũ",
        email: "dummyemail21@gmail.com",
        phoneNumber: "0934567890",
        birthday: "2010-07-16",
        status: "Active",
        hasDesireClass: "false",
    },
    {
        fullName: "Ngô Thị Yến",
        email: "dummyemail22@gmail.com",
        phoneNumber: "0945678901",
        birthday: "2005-01-25",
        status: "Deleted",
        hasDesireClass: "false",
    },
    {
        fullName: "Dương Minh Duy",
        email: "dummyemail23@gmail.com",
        phoneNumber: "0956789012",
        birthday: "2006-06-21",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Lý Thị Lan",
        email: "dummyemail24@gmail.com",
        phoneNumber: "0967890123",
        birthday: "2009-12-19",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Nguyễn Thị Tuyết",
        email: "dummyemail25@gmail.com",
        phoneNumber: "0978901234",
        birthday: "2008-04-15",
        status: "Deleted",
        hasDesireClass: "true",
    },
    {
        fullName: "Trần Thị Dung",
        email: "dummyemail26@gmail.com",
        phoneNumber: "0989012345",
        birthday: "2006-02-27",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Lê Minh Vũ",
        email: "dummyemail27@gmail.com",
        phoneNumber: "0901234566",
        birthday: "2011-08-30",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Phạm Anh Quân",
        email: "dummyemail28@gmail.com",
        phoneNumber: "0912345675",
        birthday: "2007-11-12",
        status: "Deleted",
        hasDesireClass: "true",
    },
    {
        fullName: "Hoàng Đức Bình",
        email: "dummyemail29@gmail.com",
        phoneNumber: "0923456786",
        birthday: "2005-06-06",
        status: "Active",
        hasDesireClass: "true",
    },
    {
        fullName: "Vũ Thị Thảo",
        email: "dummyemail30@gmail.com",
        phoneNumber: "0934567897",
        birthday: "2010-09-09",
        status: "Active",
        hasDesireClass: "true",
    },
];
