import {StudentInfo} from "./student-info";

export const StudentDummyData: StudentInfo[] = [
    {
        fullName: "Nguyễn Minh Đức",
        studentCode: "EN3101",
        birthday: "19/01/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Trần Thị Minh Thư",
        studentCode: "EN3102",
        birthday: "05/03/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Lê Anh Tuấn",
        studentCode: "EN3103",
        birthday: "11/02/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Phạm Thị Lan",
        studentCode: "EN3104",
        birthday: "23/07/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Nguyễn Văn Nam",
        studentCode: "EN3105",
        birthday: "15/04/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Hoàng Thị Bích",
        studentCode: "EN3106",
        birthday: "30/05/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Đặng Văn Hùng",
        studentCode: "EN3107",
        birthday: "09/01/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Bùi Thị Hằng",
        studentCode: "EN3108",
        birthday: "14/02/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Vũ Văn Hải",
        studentCode: "EN3109",
        birthday: "25/03/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Phạm Thị Mai",
        studentCode: "EN3110",
        birthday: "12/04/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Lý Minh Khoa",
        studentCode: "EN3111",
        birthday: "28/06/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Trần Thị Thu",
        studentCode: "EN3112",
        birthday: "17/07/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Nguyễn Văn Bình",
        studentCode: "EN3113",
        birthday: "04/08/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Hoàng Thị Ngọc",
        studentCode: "EN3114",
        birthday: "13/09/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Đinh Văn Đức",
        studentCode: "EN3115",
        birthday: "02/10/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Phan Thị Hoa",
        studentCode: "EN3116",
        birthday: "27/11/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Vũ Minh Phát",
        studentCode: "EN3117",
        birthday: "18/12/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Lê Thị Thanh",
        studentCode: "EN3118",
        birthday: "08/01/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Phạm Văn An",
        studentCode: "EN3119",
        birthday: "22/02/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Nguyễn Thị Nhung",
        studentCode: "EN3120",
        birthday: "15/03/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Trần Văn Dũng",
        studentCode: "EN3121",
        birthday: "07/04/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Bùi Thị Hồng",
        studentCode: "EN3122",
        birthday: "20/05/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Đặng Văn Lâm",
        studentCode: "EN3123",
        birthday: "06/06/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Lý Thị Huyền",
        studentCode: "EN3124",
        birthday: "19/07/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Nguyễn Minh Hoàng",
        studentCode: "EN3125",
        birthday: "11/08/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Phan Thị Lan Anh",
        studentCode: "EN3126",
        birthday: "03/09/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Vũ Văn Long",
        studentCode: "EN3127",
        birthday: "24/10/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Lê Thị Nguyệt",
        studentCode: "EN3128",
        birthday: "05/11/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Nguyễn Văn Tài",
        studentCode: "EN3129",
        birthday: "16/12/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Hoàng Thị Hương",
        studentCode: "EN3130",
        birthday: "09/01/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Đinh Văn Hải",
        studentCode: "EN3131",
        birthday: "12/02/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Phạm Thị Trang",
        studentCode: "EN3132",
        birthday: "22/03/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Nguyễn Văn Quân",
        studentCode: "EN3133",
        birthday: "01/04/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Trần Thị Kim",
        studentCode: "EN3134",
        birthday: "15/05/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Bùi Văn Khánh",
        studentCode: "EN3135",
        birthday: "23/06/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Đặng Thị Phương",
        studentCode: "EN3136",
        birthday: "04/07/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Vũ Văn Thành",
        studentCode: "EN3137",
        birthday: "27/08/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Lê Thị Thuỷ",
        studentCode: "EN3138",
        birthday: "17/09/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Phan Văn Quý",
        studentCode: "EN3139",
        birthday: "11/10/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Nguyễn Thị Liên",
        studentCode: "EN3140",
        birthday: "05/11/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Trần Văn Toàn",
        studentCode: "EN3141",
        birthday: "24/12/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Bùi Thị Minh",
        studentCode: "EN3142",
        birthday: "06/01/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Đặng Văn Tiến",
        studentCode: "EN3143",
        birthday: "10/02/2003",
        tuitionPaid: "false",
    },
    {
        fullName: "Lý Thị Thuỷ",
        studentCode: "EN3144",
        birthday: "21/03/2003",
        tuitionPaid: "true",
    },
    {
        fullName: "Nguyễn Văn Thiện",
        studentCode: "EN3145",
        birthday: "13/04/2003",
        tuitionPaid: "true",
    },
];
