import {TuitionPopupColumns} from "./types";

export const tuitionPopupDummyData: TuitionPopupColumns[] = [
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
    {
        time: "Jan, 2024",
        numberOfSession: "8",
        monthlyPayment: "400$",
        discount: "10%",
        status: "Paid",
    },
];
